on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Automatic PR Generator Job
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Run Maven Dependency Tree
        run: mvn dependency:tree -DoutputType=txt -DoutputFile=dependency.txt

      - name: List Contents of Current Directory
        run: ls -a

      - name: List ENV Varaiables
        run: env

      - name: List PWD
        run: pwd

      - name: Comment Action Step 1
        uses: /JanitSri/ga-jacoco-coverage@v1.12
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}