on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Automatic PR Generator Job
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Run Maven Dependency Tree
        run: mvn dependency:tree -DoutputType=graphml -DoutputFile=dependency.graphml

      - name: List Contents of Current Directory
        run: ls -a

      - name: List ENV Varaiables
        run: env

      - name: List PWD
        run: pwd

      - name: Create PR
        uses: /JanitSri/ga-jacoco-coverage@v1.13
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          filename: dependency.graphml